MusicShop/MusicShop/Models/Product/ProductCreateVM.cs
using MusicShop.Models.Brand;
using MusicShop.Models.Category;

using System.ComponentModel.DataAnnotations;

namespace MusicShop.Models.Product
{
    public class ProductCreateVM
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [MaxLength(30)]
        [Display(Name = "Product Name")]
        public string ProductName { get; set; } = null!;

        [Required]
        [Display(Name = "Description")]
        public string Description { get; set; } = null!;

        [Required]
        [Display(Name = "Brand")]
        public int BrandId { get; set; }
        public virtual List<BrandPairVM> Brands { get; set; } = new List<BrandPairVM>();

        [Required]
        [Display(Name = "Category")]
        public int CategoryId { get; set; } 
        public virtual List<CategoryPairVM> Categories { get; set; } = new List<CategoryPairVM>();
        [Display(Name = "Picture")]
        public string Picture { get; set; } = null!;
        [Range(0, 500)]
        [Display(Name = "Quantity")]
        public int Quantity { get; set; }
        [Range(0, 50000)]
        [Display(Name = "Price")]
        public decimal Price { get; set; }
        [Range(0, 100)]
        [Display(Name = "Discount")]
        public decimal Discount { get; set; }
    }
}

MusicShop/MusicShop/Models/Product/ProductDeleteVM.cs
using System.ComponentModel.DataAnnotations;

namespace MusicShop.Models.Product
{
    public class ProductDeleteVM
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Product Name")]
        public string ProductName { get; set; } = null!;

        [Display(Name = "Description")]
        public string Description { get; set; } = null!;

        public int BrandId { get; set; }
        [Display(Name = "Brand")]
        public string BrandName { get; set; } = null!;
        public int CategoryId { get; set; }
        [Display(Name = "Category")]
        public string CategoryName { get; set; } = null!;
        [Display(Name = "Picture")]
        public string Picture { get; set; } = null!;

        [Display(Name = "Quantity")]
        public int Quantity { get; set; }

        [Display(Name = "Price")]
        public decimal Price { get; set; }

        [Display(Name = "Discount")]
        public decimal Discount { get; set; }
    }

}

MusicShop/MusicShop/Models/Product/ProductDetailsVM.cs
using Humanizer.Localisation.TimeToClockNotation;

using System.ComponentModel.DataAnnotations;

namespace MusicShop.Models.Product
{
    public class ProductDetailsVM
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Product Name")]
        public string ProductName { get; set; } = null!;

        public int BrandId { get; set; }
        [Display(Name ="Brand")]
        public string BrandName { get; set;} = null!;
        public int CategoryId { get; set; }
        [Display(Name ="Category")]
        public string CategoryName { get; set; } = null!;
        [Display(Name = "Picture")]
        public string Picture {  get; set; } = null!;

        [Display(Name ="Quantity")]
        public int Quantity { get; set;}

        [Display(Name = "Price")]
        public decimal Price { get; set; }

        [Display(Name ="Discount")]
        public decimal Discount { get; set; }
    }
}

MusicShop/MusicShop/Models/Product/ProductEditVM.cs
using MusicShop.Models.Brand;
using MusicShop.Models.Category;

using System.ComponentModel.DataAnnotations;

namespace MusicShop.Models.Product
{
    public class ProductEditVM
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [MaxLength(30)]
        [Display(Name = "Product Name")]
        public string ProductName { get; set; } = null!;

        [Required]
        [Display(Name = "Description")]
        public string Description { get; set; } = null!;

        [Required]
        [Display(Name = "Brand")]
        public int BrandId { get; set; }
        public virtual List<BrandPairVM> Brands { get; set; } = new List<BrandPairVM>();

        [Required]
        [Display(Name = "Category")]
        public int CategoryId { get; set; }
        public virtual List<CategoryPairVM> Categories { get; set; } = new List<CategoryPairVM>();

        [Display(Name = "Picture")]
        public string Picture { get; set; } = null!;
        [Range(0, 500)]
        [Display(Name ="Quantity")]
        public int Quantity { get; set; }
        [Range(0, 50000)]
        [Display(Name = "Price")]
        public decimal Price { get; set; }
        [Range(0, 100)]
        [Display(Name = "Discount")]
        public decimal Discount { get; set; }
    }
}

MusicShop/MusicShop/Models/Product/ProductIndexVM.cs
using System.ComponentModel.DataAnnotations;

namespace MusicShop.Models.Product
{
    public class ProductIndexVM
    {
        [Key]
        public int Id { get; set; }

        [Display(Name ="Product Name")]
        public string ProductName { get; set; }

        public int BrandId { get; set; }
        [Display(Name ="Brand")]
        public string BrandName { get; set;}
        public int CategoryId { get; set; }
        [Display(Name ="Category")]
        public string CategoryName { get; set; }
        [Display(Name = "Picture")]
        public string Picture {  get; set; }
        [Display(Name ="Quantity")]
        public int Quantity { get; set; }
        [Display(Name ="Price")]
        public decimal Price { get; set; }
        [Display(Name ="Discount")]
        public decimal Discount { get; set; }

    }
}

MusicShop/MusicShop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

using MusicShop.Core.Contracts;
using MusicShop.Infrastructure.Data.Entities;
using MusicShop.Models.Brand;
using MusicShop.Models.Category;
using MusicShop.Models.Product;

namespace MusicShop.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly IBrandService _brandService;
        public ProductController(IProductService productService, ICategoryService categoryService, IBrandService brandService)
        {
            this._productService = productService;
            this._categoryService = categoryService;
            this._brandService = brandService;
        }


        // GET: ProductController
        [AllowAnonymous]
        public ActionResult Index(string searchStringCategoryName, string searchStringBrandName)
        {
            List<ProductIndexVM> products = _productService.GetProducts(searchStringCategoryName, searchStringBrandName)
                .Select(product => new ProductIndexVM
                {
                    Id = product.Id,
                    ProductName = product.ProductName,
                    BrandId = product.BrandId,
                    BrandName = product.Brand.BrandName,
                    CategoryId = product.CategoryId,
                    CategoryName = product.Category.CategoryName,
                    Picture = product.Picture,
                    Quantity = product.Quantity,
                    Price = product.Price,
                    Discount = product.Discount

                }).ToList();
            return this.View(products);
        }

        // GET: ProductController/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            Product item = _productService.GetProductById(id);
            if (item == null)
            {
                return NotFound();

            }
            ProductDetailsVM product = new ProductDetailsVM()
            {
                Id = item.Id,
                ProductName = item.ProductName,
                Description = item.Description,
                BrandId = item.BrandId,
                BrandName = item.Brand.BrandName,
                CategoryId = item.CategoryId,
                CategoryName = item.Category.CategoryName,
                Picture = item.Picture,
                Quantity = item.Quantity,
                Price = item.Price,
                Discount = item.Discount
            };
            return View(product);
        }

        // GET: ProductController/Create
        public ActionResult Create()
        {
            var product = new ProductCreateVM();
            product.Brands = _brandService.GetBrands()
                .Select(x => new BrandPairVM()
                {
                    Id = x.Id,
                    Name = x.BrandName
                }).ToList();
            product.Categories = _categoryService.GetCategories()
                .Select(x => new CategoryPairVM()
                {
                    Id = x.Id,
                    Name = x.CategoryName
                }).ToList();

            return View(product);
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm] ProductCreateVM product)
        {
            if (ModelState.IsValid)
            {
                var createdId = _productService.Create(product.ProductName, product.Description, product.BrandId, product.CategoryId, product.Picture, product.Quantity, product.Price, product.Discount);
                if (createdId)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View();

        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(int id)
        {
            Product product = _productService.GetProductById(id);
            if (product == null)
            {
                return NotFound();
            }
            ProductEditVM updatedProduct = new ProductEditVM()
            {
                Id = product.Id,
                ProductName = product.ProductName,
                Description = product.Description,
                BrandId = product.BrandId,
                CategoryId = product.CategoryId,
                Picture = product.Picture,
                Quantity = product.Quantity,
                Price = product.Price,
                Discount = product.Discount
            };
            updatedProduct.Brands = _brandService.GetBrands()
                .Select(b => new BrandPairVM()
                {
                    Id = b.Id,
                    Name = b.BrandName
                }).ToList();
            updatedProduct.Categories = _categoryService.GetCategories()
                .Select(b => new CategoryPairVM()
                {
                    Id = b.Id,
                    Name = b.CategoryName
                }).ToList();
            return View(updatedProduct);
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ProductEditVM product)
        {
            if (ModelState.IsValid)
            {
                var updated = _productService.Update(id, product.ProductName, product.Description, product.BrandId, product.CategoryId, product.Picture, product.Quantity, product.Price, product.Discount);
                if (updated)
                {
                    return this.RedirectToAction("Index");
                }
            }
            return View(product);
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            Product item = _productService.GetProductById(id);
            if (item == null)
            {
                return NotFound();
            }
            ProductDeleteVM product = new ProductDeleteVM()
            {
                Id = item.Id,
                ProductName = item.ProductName,
                Description = item.Description,
                BrandId = item.BrandId,
                BrandName = item.Brand.BrandName,
                CategoryId = item.CategoryId,
                CategoryName = item.Category.CategoryName,
                Picture = item.Picture,
                Quantity = item.Quantity,
                Price = item.Price,
                Discount = item.Discount
            };

            return View(product);
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            var deleted = _productService.RemoveById(id);
            if (deleted)
            {
                return this.RedirectToAction("Success");
            }
            else
            {
                return View();
            }
        }
        public ActionResult Success()
        {
            return View();
        }

       
       
    }
}

MusicShop/MusicShop/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MusicShop.Core.Contracts;
using MusicShop.Core.Services;
using MusicShop.Models.ShoppingCart;
using System.Security.Claims;

namespace MusicShop.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCartService _cartService;
        private readonly IOrderService _orderService;
        private readonly IProductService _productService;

        public ShoppingCartController(IShoppingCartService cartService, IOrderService orderService, IProductService productService)
        {
            _cartService = cartService;
            _orderService = orderService;
            _productService = productService;
        }
        [HttpPost]
        public ActionResult AddToCart(int productId, int quantity)
        {
            string currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            _cartService.AddToCart(productId, currentUserId, quantity);
            return RedirectToAction("Index");
        }
        public ActionResult PlaceOrder()
        {
            string currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var cartItems = _cartService.GetShoppingCartByUser(currentUserId);

            // Create order from cart items
            _orderService.CreateOrderFromCart(cartItems);
            // Clear the shopping cart
            _cartService.ClearCart(currentUserId);
            // Redirect to order success page or home page
            return RedirectToAction("OrderSuccess");
        }
        [HttpPost]
        public ActionResult RemoveFromCart(int cartItemId)
        {
            _cartService.RemoveFromCart(cartItemId);


            return RedirectToAction("Index");
        }
        public ActionResult OrderSuccess()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UpdateCart(int cartItemId, int quantity)
        {
            try
            {
                _cartService.UpdateCart(cartItemId, quantity);
                return RedirectToAction("Index");
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            catch (InvalidOperationException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Error updating cart.");
            }
            string currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var cartItems = _cartService.GetShoppingCartByUser(currentUserId);
            return View("Index", cartItems);
        }

        public ActionResult ClearCart()
        {
            string currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            _cartService.ClearCart(currentUserId);
            return RedirectToAction("Index");
        }
        // GET: ShoppingCartController
        public ActionResult Index()
        {
            string currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            List<ShoppingCartIndexVM> cartItems = _cartService.GetShoppingCartByUser(currentUserId)
           .Select(item => new ShoppingCartIndexVM
           {
               Id = item.Id,
               ProductName = item.Product.ProductName,
               Quantity = item.Quantity,
               QuantityInStock = item.Product.Quantity,
               Price = item.Product.Price,
               Discount = item.Product.Discount,
               UserId = currentUserId,
           }).ToList();
            return View(cartItems);

        }
    }
}

MusicShop/MusicShop/Views/Product/Create.cshtml
@model MusicShop.Models.Product.ProductCreateVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                @*<input asp-for="BrandId" class="form-control" />*@
                <select asp-for="BrandId" class="form-control text-center">
                    @foreach (var brand in Model.Brands)
                    {
                        <option value=" @brand.Id">@brand.Name</option>
                    }
                </select>
                <span asp-validation-for="BrandId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                @*<input asp-for="CategoryId" class="form-control" />*@
                <select asp-for="CategoryId" class="form-control text-center">
                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MusicShop/MusicShop/Views/Product/Delete.cshtml
@model MusicShop.Models.Product.ProductDeleteVM

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductDeleteVM</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BrandName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BrandName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class="col-sm-10">
            <img src="@Html.DisplayFor(model => model.Picture)" alt="Image" width="100" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MusicShop/MusicShop/Views/Product/Details.cshtml
@model MusicShop.Models.Product.ProductDetailsVM

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    
   
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BrandName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BrandName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class="col-sm-10">
            <img src="@Html.DisplayFor(model => model.Picture)" alt="Image" width="300"  />
            @*@Html.DisplayFor(model => model.Picture)*@
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MusicShop/MusicShop/Views/Product/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
@model IEnumerable<MusicShop.Models.Product.ProductIndexVM>
@{
    ViewData["Title"] = "Index";
}
<h1>@Localizer["All products"]</h1>

 @if((this.User.Identity.IsAuthenticated) && (this.User.IsInRole("Administrator")))
 {
     <p>
          <a asp-action="Create">Create New</a>
     </p>
 }

<form asp-controller="Product" asp-action="Index" method="get">
    <p>
        Brand: <input type="text" name="SearchStringBrandName" />
        Category: <input type="text" name="SearchStringCategoryName" />

        <input type="submit" value="Filter" />
    </p>
</form>


<div class="row">
    @foreach (var item in Model)
    {
        <div class="card" style="width: 18rem;">
            <a asp-action="Details" asp-route-id="@item.Id" class="btn">
                <img src="@Html.DisplayFor(modelItem => item.Picture)" class="card-img-top" alt="product img" max-width:100%; />
            </a>
            <div class="card-body">

                <h5 class="card-title">
                    @Html.DisplayFor(modelItem => item.ProductName)
                </h5>
                <h6 class="card-text text-danger">@Html.DisplayFor(modelItem => item.Price) lv.</h6>
                
                @if ((this.User.Identity.IsAuthenticated) && (this.User.IsInRole("Administrator")))
                {
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn text-dark">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
                    </svg>
                  </a>
                }
                @if ((this.User.Identity.IsAuthenticated) && (this.User.IsInRole("Administrator")))
                {
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5" />
                        </svg>
                    </a>
                }
                @if (this.User.Identity.IsAuthenticated)
                {
                    <form asp-action="AddToCart" asp-controller="ShoppingCart" method="post">
                        <input type="hidden" name="productId" value="@item.Id" />
                        <button type="submit" class="btn btn-primary">Add to Cart</button>
                    </form>
                    <form asp-action="Add" asp-controller="Wishlist" method="post">
                        <input type="hidden" name="productId" value="@item.Id" />
                        <button type="submit" class="btn btn-primary">Wishlist</button>
                    </form>
                   
                }
            </div>
        </div>
           
    }
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MusicShop/MusicShop/Views/Product/Success.cshtml
@{
    ViewData["Title"] = "Success";
}

<div class="text-center">
    <h1 class="display-4">Successfuly deleted!</h1>
   
        <a asp-action="Index">Back to List</a>
    
</div>