MusicShop/MusicShop/Models/Wishlists/WishlistDTO.cs
namespace MusicShop.Models.Wishlist
{
    public class WishlistDTO
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Picture { get; set; }
        public decimal Price { get; set; }
    }
}

MusicShop/MusicShop/Controllers/WishlistController.cs
using Castle.Core.Internal;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MusicShop.Core.Contracts;
using MusicShop.Models.Wishlist;
using System.Security.Claims;

namespace MusicShop.Controllers
{
    [Authorize]
    public class WishListController : Controller
    {
        private readonly IWishlistService _wishListService;
        private readonly IProductService _productService;

        public WishListController(IWishlistService wishListService, IProductService productService)
        {
            _wishListService = wishListService;
            _productService = productService;
        }

        public IActionResult Index()
        {
            var currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var wishList = _wishListService.GetWishListByUserId(currentUserId);
         

            var model = wishList.Select(w => new WishlistDTO
            {
                Id = w.Id,
                ProductId = w.Product.Id,
                ProductName = w.Product.ProductName,
                Picture = w.Product.Picture,
                Price = w.Product.Price
            }).ToList();

            return View(model);
        }
        [HttpPost]
        public IActionResult Add(int productId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }

            _wishListService.AddToWishList(userId, productId);
            return RedirectToAction("Index");
        }

        public IActionResult Remove(int productId)
        {
            var currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            _wishListService.RemoveFromWishList(currentUserId, productId);
            if (currentUserId == null) return NotFound();
            return RedirectToAction(nameof(Index));
        }
    }
}

MusicShop/MusicShop/Views/Wishlist/Index.cshtml
@model List<MusicShop.Models.Wishlist.WishlistDTO>
@{
    ViewData["Title"] = "Index";
}
<h2>My Wish List</h2>

<table class="table">
    <thead>
        <tr>
            <th>Image</th>
            <th>Product Name</th>
            <th>Price</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td><img src="@item.Picture" width="50" /></td>
                <td>@item.ProductName</td>
                <td>@item.Price.ToString("C")</td>
                <td>
                    <a href="@Url.Action("Remove", "WishList", new { productId = item.ProductId })" class="btn btn-danger">Remove</a>
                </td>
            </tr>
        }
    </tbody>
</table>